version: '3.9'

services:
  app:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:5432 -- uvicorn main:app --host 0.0.0.0 --port 5002 --reload"
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
